# Generated by Django 4.2.7 on 2023-11-17 18:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parser', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mark',
            name='mark_name',
            field=models.CharField(max_length=64),
        ),
        migrations.AlterField(
            model_name='model',
            name='body_type',
            field=models.CharField(max_length=64, null=True),
        ),
        migrations.AlterField(
            model_name='model',
            name='model_name',
            field=models.CharField(max_length=64),
        ),
        migrations.AlterField(
            model_name='model',
            name='modification',
            field=models.CharField(max_length=64, null=True),
        ),
        migrations.AlterField(
            model_name='model',
            name='years',
            field=models.CharField(max_length=64, null=True),
        ),
    ]
