# Generated by Django 3.1.4 on 2023-11-18 08:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('parser', '0003_auto_20231118_1101'),
    ]

    operations = [
        migrations.AddField(
            model_name='model',
            name='mark',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='all_models', to='parser.mark'),
            preserve_default=False,
        ),
    ]
